name: Build Unity project
on:
  push:
    branches:
      - master
jobs:
  activation:
    name: Build Unity project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Chronotator-StandaloneWindows64
          restore-keys: |
            Library-Chronotator-
            Library-
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
      - name: Delete Existing Artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 second'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build